# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79313da9dbeb21f116bcec58bdab03d0d9dc429d85fa91d94057f1a126e7ba84877c6f2edccb880e4f9e686608aef93ba8a2f33dc764be2f44712d5c08a4915e

test:
  secret_key_base: 5b84c29ddf38d2a4ae996e2566cd4e7de19cc1548b5c8f733e54e65e45bb023d6fa3125b6d08735c9aa2a346af480840a0c49b2ce59f053a5e092c4db5472a3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
